# Generated by Django 3.2.8 on 2021-10-26 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_email_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='destination',
            field=models.CharField(max_length=120, validators=[django.core.validators.EmailValidator]),
        ),
    ]
