# Generated by Django 3.2.8 on 2021-10-26 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_email_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='created_document_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
